#!/bin/bash

PLATFORM=`uname`

# find V-REP executable
if [[ "$PLATFORM" = "Darwin" ]]; then
    # Mac platform
    if [[ -x ../../vrep.app/Contents/MacOS/vrep ]]; then
        VREP="../../vrep.app/Contents/MacOS/vrep"
    fi
elif [[ "$PLATFORM" = "Linux" ]]; then
    # Linux platform
    :
fi

if [[ ! -x "$VREP" ]]; then
    echo "Please fix me: I don't know ho to find V-REP executable on this platform ($PLATFORM)" 1>&2
    exit 1
fi

SCENE="$1"

if [[ -f "$PWD/$SCENE" ]]; then
    SCENE="$PWD/$SCENE"
fi

"$VREP" -h -s -q "$1"

