#!/bin/bash

PLATFORM=`uname`

# find CoppeliaSim executable
if [[ "$PLATFORM" = "Darwin" ]]; then
    # Mac platform
    if [[ -x ../../coppeliaSim.app/Contents/MacOS/coppeliaSim ]]; then
        COPPELIASIM="../../coppeliaSim.app/Contents/MacOS/coppeliaSim"
    fi
elif [[ "$PLATFORM" = "Linux" ]]; then
    # Linux platform
    :
fi

if [[ ! -x "$COPPELIASIM" ]]; then
    echo "Please fix me: I don't know ho to find CoppeliaSim executable on this platform ($PLATFORM)" 1>&2
    exit 1
fi

SCENE="$1"

if [[ -f "$PWD/$SCENE" ]]; then
    SCENE="$PWD/$SCENE"
fi

"$COPPELIASIM" -h -s -q "$1"

